name: Check PR title
on:
  pull_request:
    branches: ['master', 'develop']
    types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Set Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@v1.0.3
