name: CI for v2

on:
  push:
    branches: [ 'master-v2' ]
  pull_request:
    branches: [ 'master-v2', 'develop-v2' ]
    types: [ 'opened', 'reopened', 'edited', 'synchronize' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cancel_previous-v2:

    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          workflow_id: ${{ github.event.workflow.id }}

  build-v2:
    needs: cancel_previous
    name: Build & Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Ruby
        uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0

      - name: Set Node 16
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install node_modules
        run: |
          npm ci

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: cache gradle dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-core-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-core-

      - name: Build
        run: |
          git fetch --no-tags --prune --depth=100 origin master-v2
          npm run build

      - name: Unit test
        run: |
          git fetch --no-tags --prune --depth=100 origin master-v2
          npm run test
