name: Check PR title
on:
  pull_request:
    branches: ['master', 'develop', 'master-mpx', 'develop-mpx']
    types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@0a83071336f7d6417249629f67a64530fcecda2e # v1.0.11
