name: Check PR title for v2
on:
  pull_request:
    branches: ['master-v2', 'develop-v2']
    types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title_v2:
    name: Check PR title for v2
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check PR title for v2
        uses: rudderlabs/github-action-check-pr-title@0a83071336f7d6417249629f67a64530fcecda2e # v1.0.11