name: Create new hotfix branch for v2

on:
  workflow_dispatch:
    inputs:
      hotfix_name:
        description: Hotfix branch name for v2
        required: true

jobs:
  create-hotfix-branch-v2:
    name: Create new branch for v2
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master-v2'
    steps:
      - name: Set env BRANCH_NAME
        run: |
              BRANCH="${{ github.event.pull_request.head.ref }}"
              echo "BRANCH_NAME=hotfix-v2" >> "$GITHUB_ENV"

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            branch: '${{ BRANCH_NAME }}/${{ github.event.inputs.hotfix_name }}-v2'
