name: Create new hotfix branch

on:
  workflow_dispatch:
    inputs:
      hotfix_name:
        description: Hotfix branch name
        required: true

jobs:
  create-branch:
    name: Create new branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/master-mpx'
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write

      - name: Set env BRANCH_NAME
        run: |
          if [[ "$GITHUB_REF_NAME" == 'master-mpx' ]]; then
            echo "BRANCH_NAME=hotfix-mpx" >> "$GITHUB_ENV"
          else
            echo "BRANCH_NAME=hotfix" >> "$GITHUB_ENV"
          fi

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          branch: '${{ env.BRANCH_NAME }}/${{ github.event.inputs.hotfix_name }}'
