name: Publish new github release

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'master', 'master-mpx' ]
    types:
      - closed

jobs:
  release:
    name: Publish new release
    runs-on: ubuntu-latest
    permissions:
      contents: read # to read repository contents
    if: startsWith(github.ref, 'refs/heads/master') || ((startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'release-mpx/') || startsWith(github.event.pull_request.head.ref, 'hotfix-release/') || startsWith(github.event.pull_request.head.ref, 'hotfix-release-mpx/')) && github.event.pull_request.merged == true) # only merged pull requests must trigger this job
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
          permission-contents: write # to create commits, tags, and releases
          permission-pull-requests: write # to create and update PRs

      - name: Extract version from branch name (for release branches)
        id: extract-version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix-}
          VERSION=${VERSION#release-mpx/}
          VERSION=${VERSION#release/}
          
          echo "release_version=$VERSION" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 16

      - name: Create Github Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          npx conventional-github-releaser -p angular

      - name: Create pull request into develop
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 # v2
        if: (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix-release/'))
        with:
          source_branch: 'master'
          destination_branch: 'develop'
          github_token: ${{ steps.generate-token.outputs.token }}
          pr_title: "chore(release): pulling main into develop post release v${{ steps.extract-version.outputs.release_version }}"
          pr_body: ':crown: *An automated PR*'
          pr_reviewer: '@rudderlabs/sdk-android'
      - name: Create pull request into develop-mpx
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 # v2
        if: (startsWith(github.event.pull_request.head.ref, 'release-mpx/') || startsWith(github.event.pull_request.head.ref, 'hotfix-release-mpx/'))
        with:
          source_branch: 'master'
          destination_branch: 'develop'
          github_token: ${{ steps.generate-token.outputs.token }}
          pr_title: "chore(release): pulling main into develop post release v${{ steps.extract-version.outputs.release_version }}"
          pr_body: ':crown: *An automated PR*'
          pr_reviewer: '@rudderlabs/sdk-android'

      - name: Delete hotfix release branch
        uses: koj-co/delete-merged-action@63a03c35810a8a7d4840d18793c0f68ff8b59450 # master
        if: startsWith(github.event.pull_request.head.ref, 'hotfix-release/')
        with:
          branches: 'hotfix-release/*'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}

      - name: Delete release branch
        uses: koj-co/delete-merged-action@63a03c35810a8a7d4840d18793c0f68ff8b59450 # master
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        with:
          branches: 'release/*'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
      - name: Delete hotfix release branch -mpx
        uses: koj-co/delete-merged-action@63a03c35810a8a7d4840d18793c0f68ff8b59450 # master
        if: startsWith(github.event.pull_request.head.ref, 'hotfix-release-mpx/')
        with:
          branches: 'hotfix-release/*'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}

      - name: Delete release branch -mpx
        uses: koj-co/delete-merged-action@63a03c35810a8a7d4840d18793c0f68ff8b59450 # master
        if: startsWith(github.event.pull_request.head.ref, 'release-mpx/')
        with:
          branches: 'release/*'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
