name: Notify Slack Channel

on:
  release:
    types: [ created ]

jobs:
  deploy-tag:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          module_name=$(echo ${{ github.event.release.tag_name }} | cut -d'-' -f1)
          echo "::set-output name=module_name::$module_name"

      - name: Send message to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "${{ secrets.SLACK_RELEASE_CHANNEL_ID }}"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New release: ${module_name}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Release: <${{ github.event.release.html_url }}|${{ github.event.release.tag_name }}>*"
                  }
                }
              ]
            }
